#%RAML 1.0 Trait 

headers:
  client_id:
    description: The client ID of the registered client application. 
    type: string
    required: true
    example: "15283cf2d08e4676a65372510e99f032"
  client_secret:
    description: The client Secret of the registered client application.
    type: string
    required: true
    example: "b306DACB094f3244720g09B80E23434e"