#%RAML 1.0 Trait
headers:
  X-Request-ID:
    description: Allows to have an unique identifier per transacion to keep in an application (it can be linked into a correlation ID)
    required: true
    example: "ee83ff80-9f8b-11ea-9440-38f9d38d94e6"